language: node_js

services:
  - docker
  
node_js:
  - "8"

before_install:
  - docker build -t dinosauce/surffinder .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

before_script:
  - npm install
script:
  - npm test
