language: node_js

services:
  - docker

python:
    version: 2.7

node_js:
  - "8"

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_script:
  - npm install
script:
  - npm test

after_success:
  - docker build -t dinosauce/surffinder:$COMMIT . # Build Image
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # Login to Docker
  - docker push dinosauce/surffinder:$COMMIT # Push Image to DockerHub
  - pip install awsebcli --upgrade --user # Install aws cli w/o sudo
  - eb --version
  - export PATH=$PATH:$HOME/.local/bin
  - sed -i'' -e "s;%BUILD_NUM%;$COMMIT;g" Dockerrun.aws.json # Replade Build number in Dockerrun file
  - zip -r $COMMIT.zip Dockerrun.aws.json # zip Dockerrun file
  - eb init -r us-west-1 surffinder
  - eb deploy -l $COMMIT
